version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  verify:
    docker:
      - image: cimg/node:21.0
    steps:
      - checkout
      - run: ls ~
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test

workflows:
  verify-workflow:
    jobs:
      - verify
