name: Continuous Integration & Delivery
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
jobs:
  verify:
    name: Validate Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Linter
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier
      - name: Run Tests
        run: npm run test
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build & Export Project
        env:
          CONTENTFUL_ENV_SPACE_ID: ${{ secrets.CONTENTFUL_ENV_SPACE_ID }}
          CONTENTFUL_ENV_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ENV_ACCESS_TOKEN }}
        run: npm run build
  deploy:
    name: Deploy Project
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Next.js Build & Export
        env:
          CONTENTFUL_ENV_SPACE_ID: ${{ secrets.CONTENTFUL_ENV_SPACE_ID }}
          CONTENTFUL_ENV_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ENV_ACCESS_TOKEN }}
        run: npm run build
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
